# Automatically build the project and run any configured tests for every push
# and submitted pull request.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - minecraft: "1.20.1"
            java: "17"
            yarn: "1.20.1+build.10"
            fabric: "0.92.2+1.20.1"
            cloth: "11.1.118"
            modmenu: "7.2.2"

          - minecraft: "1.21.1"
            java: "21"
            yarn: "1.21.1+build.3"
            fabric: "0.102.0+1.21.1"
            cloth: "15.0.140"
            modmenu: "11.0.3"

          - minecraft: "1.21.4"
            java: "21"
            yarn: "1.21.4+build.4"
            fabric: "0.114.1+1.21.4"
            cloth: "15.0.140"
            modmenu: "11.0.3"

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build mod
        run: ./gradlew build -Pminecraft_version=${{ matrix.minecraft }} -Pyarn_mappings=${{ matrix.yarn }} -Pfabric_version=${{ matrix.fabric }} -Pjava_version=${{ matrix.java }} -Pcloth_config_version=${{ matrix.cloth }} -Pmodmenu_version=${{ matrix.modmenu }}

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.minecraft }}
          path: build/libs/